backend:
  name: github
  repo: trojanshakib/baal.xyz
  local_backend: true

media_folder: content/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title }
      - { name: subTitle, label: Sub Title }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author }
      - { name: authorLink, label: Author Link }
      - { name: categories, label: Categories, widget: list }
      - { name: featuredImage, label: Featured Image, widget: image }
      - { name: featuredImageCaption, label: Featured Image Caption }
      - { name: socialImage, label: Social Image, widget: image }
      - { name: draft, label: Draft, widget: boolean, default: true }
      - { name: body, label: Body, widget: markdown }
      
  - name: page
    label: Page
    folder: content/pages
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown, default: '<SEO title="" description=""/>' }